language: generic

sudo: required

services: 
    - docker

before_install:
    - docker build -t 23david73/react-test -f ./client/Dockerfile.dev ./client

script: 
    - docker run -e CI=true 23david73/react-test npm run test

after_success:
    - docker build -t 23david73/multi-client ./client
    - docker build -t 23david73/multi-nginx ./nginx
    - docker build -t 23david73/multi-server ./server
    - docker build -t 23david73/multi-worker ./worker

    # Authenticate with Dockerhub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Push to Dockerhub
    - docker push 23david73/multi-client
    - docker push 23david73/multi-nginx
    - docker push 23david73/multi-server
    - docker push 23david73/multi-worker

deploy: 
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker-react
    env: MultiDockerReact-env
    bucket_name: elasticbeanstalk-us-east-2-816219623859
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    