sudo: required
services: 
    - docker

before_install:
    - docker build 23david73/react-test -f ./client/Dockerfile.dev ./client

script: 
    - docker run -e CI=true 23david73/react-test npm test

after_success:
    - docker build -t 23david73/multi-client ./client
    - docker build -t 23david73/multi-nginx ./nginx
    - docker build -t 23david73/multi-server ./server
    - docker build -t 23david73/multi-worker ./worker

language: generic

# Authenticate with Dockerhub
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Push to Dockerhub
- docker push 23david73/multi-client
- docker push 23david73/multi-nginx
- docker push 23david73/multi-server
- docker push 23david73/multi-worker